%%% Loading DATA
load depthgauge_data_set1.mat

%%% Ploting xy-scatter diagram
figure(1); 
scatter(x,z,'*','g');
hold on;
xlabel('x') % x-axis label
ylabel('z') % y-axis label
title('xy-scatter') 


%%% LINEAR ESTIMATOR

    Exz=mean(x.*z); %Estimation of xz 
    Ezz=mean(z.*z); %Estimation of z^2

      
Alpha=Exz/Ezz; % alpha 
x_lmse=Alpha*z; %x value generated by linear mean square error estimator
plot(x_lmse,z,'b . ');
 


%% 

%%% UNBIASED LINEAR ESTIMATOR

alpha=cov(x,z)/var(z);%alpha
Ex=mean(x);%Estimation of x 
Alpha1=alpha(2,1);%covariance is in the anti diagonal terms  
Ez=mean(z);%Estimation of z

beta= Ex- Alpha1*(Ez) ; 
%x value generated by unbiased linear mean square error estimator 
x_ulmse=Alpha1*(z)+beta ;
plot(x_ulmse,z,'r . ');
legend('x','x linear mse','x unbiased linear mse');  
hold off;   


%% 
%%% Loading second data set
load depthgauge_data_set2.mat
% Linear estimation
    Exz1=mean(x.*z); %Estimation of xz 
    Ezz1=mean(z.*z); %Estimation of z^2   
alpha1=Exz1/Ezz1;
 %x value generated by linear mean square error estimator
x_lmse1=alpha1*z;
x_EstError=x_lmse1-x;%estimation error
Bias_overall=mean(x_EstError);%Over all bias
Var_error=var(x_EstError);%Variance of estimation error


%%  
% Unbiased Linear estimation
alpha2=cov(x,z)/var(z);
Ex2=mean(x);%Estimation of x 
Ez2=mean(z);%Estimation of z
%covariance is in the anti diagonal terms  
beta2= Ex2 - alpha2(2,1)*(Ez2) ; 
 %x value generated by unbiased linear mean square error estimator
x_ulmse2=alpha2(2,1)*(z)+beta2 ; 
x_EstError2=x_ulmse2-x;%estimation error
Bias_overall2=mean(x_EstError2);%Over all bias
Var_error2=var(x_EstError2);%Variance of estimation error
